CREATE TABLE character_armours (
    id INT PRIMARY KEY AUTO_INCREMENT,
    character_id INT NOT NULL,
    armour_id INT NOT NULL,
    equipped BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (character_id) REFERENCES characters(id) ON DELETE CASCADE,
    FOREIGN KEY (armour_id) REFERENCES armours(id) ON DELETE RESTRICT
)