DROP TABLE IF EXISTS chats;
CREATE TABLE chats (
  id INT PRIMARY KEY AUTO_INCREMENT,
  campaign_id INT NOT NULL UNIQUE,
  conversation_path VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (campaign_id) REFERENCES campaigns (id) ON DELETE CASCADE
)
