CREATE DATABASE DND_DATABASE;
USE DND_DATABASE;

DROP TABLE IF EXISTS accounts;
CREATE TABLE accounts (
    id INT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS campaigns;
CREATE TABLE campaigns (
    id INT PRIMARY KEY AUTO_INCREMENT,
    account_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    state VARCHAR(50) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS races;
CREATE TABLE races (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    health INT NOT NULL,
    attack INT NOT NULL,
    defense INT NOT NULL,
    sprite_path VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS classes;
CREATE TABLE classes (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    health INT NOT NULL,
    attack INT NOT NULL,
    defense INT NOT NULL,
    sprite_path VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS armours;
CREATE TABLE armours (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    rarity INT NOT NULL,
    health INT NOT NULL,
    description TEXT,
    sprite_path VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_rarity (rarity)
);

DROP TABLE IF EXISTS weapons;
CREATE TABLE weapons (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    rarity INT NOT NULL,
    attack INT NOT NULL,
    description TEXT,
    sprite_path VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_rarity (rarity)
);

DROP TABLE IF EXISTS shields;
CREATE TABLE shields (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    rarity INT NOT NULL,
    defense INT NOT NULL,
    description TEXT,
    sprite_path VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_rarity (rarity)
);


DROP TABLE IF EXISTS items;
CREATE TABLE items (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE,
    rarity INT NOT NULL,
    stat_modified VARCHAR(50) NOT NULL, -- 'health', 'attack', 'defense'
    stat_value INT NOT NULL, -- Can be positive or negative
    description TEXT,
    sprite_path VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_rarity (rarity)
);

DROP TABLE IF EXISTS characters;
CREATE TABLE characters (
    id INT PRIMARY KEY AUTO_INCREMENT,
    race_id INT NOT NULL,
    class_id INT NOT NULL,
    campaign_id INT NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    current_health INT NOT NULL,
    max_health INT NOT NULL,
    attack INT NOT NULL,
    defense INT NOT NULL,
    sprite_path VARCHAR(255),
    armour_id INT DEFAULT NULL,
    weapon_id INT DEFAULT NULL,
    shield_id INT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (race_id) REFERENCES races (id) ON DELETE RESTRICT,
    FOREIGN KEY (class_id) REFERENCES classes (id) ON DELETE RESTRICT,
    FOREIGN KEY (campaign_id) REFERENCES campaigns (id) ON DELETE CASCADE,
    FOREIGN KEY (armour_id) REFERENCES armours (id) ON DELETE RESTRICT,
    FOREIGN KEY (weapon_id) REFERENCES weapons (id) ON DELETE RESTRICT,
    FOREIGN KEY (shield_id) REFERENCES shields (id) ON DELETE RESTRICT
);

DROP TABLE IF EXISTS character_items;
CREATE TABLE character_items (
    id INT PRIMARY KEY AUTO_INCREMENT,
    character_id INT NOT NULL,
    item_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (character_id) REFERENCES characters (id) ON DELETE CASCADE,
    FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE RESTRICT
);


DROP TABLE IF EXISTS chats;
CREATE TABLE chats (
    id INT PRIMARY KEY AUTO_INCREMENT,
    campaign_id INT NOT NULL UNIQUE,
    conversation_path VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (campaign_id) REFERENCES campaigns (id) ON DELETE CASCADE
);


DROP TABLE IF EXISTS enemies;
CREATE TABLE enemies (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    difficulty INT NOT NULL,
    health INT NOT NULL,
    attack INT NOT NULL,
    defense INT NOT NULL,
    sprite_path VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_difficulty (difficulty)
);


DROP TABLE IF EXISTS logs;
CREATE TABLE logs (
    id INT PRIMARY KEY AUTO_INCREMENT,
    campaign_id INT, -- * used to be nullable for ON DELETE SET NULL
    message TEXT NOT NULL,
    event_number INT NOT NULL,
    event_type VARCHAR(50),
    event_data JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (campaign_id) REFERENCES campaigns (id) ON DELETE CASCADE,
    UNIQUE (campaign_id, event_number)
);

DELIMITER $$
CREATE TRIGGER logs_campaign_id_not_null
BEFORE INSERT ON logs
FOR EACH ROW
BEGIN
  IF NEW.campaign_id IS NULL THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'campaign_id cannot be NULL on insert';
  END IF;
END$$
DELIMITER ;

